### ISSUE TITLE
Mobile Landscape - should look like Tablet's landscape

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#104]

**Comment by Artemk23** [comment]
1. Welcome screen image should be full screen, no white areas should be visible
2. While scrolling down black "MAVEN" header should be hidden as well and appear only by scrolling down - PORTRAIT AS WELL
3. "Moving In" effect should be removed for all Manufacturers
4. "Request More Info" image should be fit full width, now image is partially covered and "MAVEN" logo is cut

**Comment by TehZarathustra** [comment]
need testing

**Comment by Artemk23** [comment]
640px width ( Galaxy S5 in the Inspector):
- "Staff" page doesn't display names on the right side of the screen, like on tablets version
- "Request More Info" pop-up screen: Contact Form doesn't fit the screen, "Submit" button is hidden and this screen should have "X" button so user can close the screen by clicking on it ( only by clicking on it)

All resolutions:
- Remove "Tap to Enlarge" text from both portrait and landscape versions, leave only "black&white" to colors effect
- Full-screen image viewer: user should be able to exit the viewer only by clicking "X" icon if user clicks on the image - panel with the title, description and "request more info" button should be hidden

**Comment by TehZarathustra** [comment]
all fixed except
- exit only by clicking "X"

i think it's a good practice on mobile to have a large area for tap to exit, moreover "X" at this moment does nothing but serves as a reference

implementing something like "if user clicks on the image - info panel should be hidden" will take an evening at best

**Comment by Artemk23** [comment]
"WHO" page:
- ~~PORTRAIT: Remove email and phone below the Name and title ( not from the image itself, only from the name descriptions)~~
- ~~LANDSCAPE: 1. Remove email and phone below the Name and title ( not from the image itself, only from the name descriptions)~~
- ~~Add "Zoom-In" effect with the email and phone displayed on the image~~
- ~~When you're at the "The Senators Group" page - photo with staff members overlapping the whole screen until you scroll further.~~

MANUFACTURERS:
~~PORTRAIT: "Senator" brand - space between the images is too large, space between the images should be like in the first brand "The Senator Group"~~
_**Issue is reproducible across all of the brands_*

ENTERING FULL SCREEN: 
- ~~now a user has to tap 3 times to enter the full-screen mode - should be 2 times~~

REQUEST MORE INFO POP-UP: 
- ~~after tapping on the text field the whole view jumps away from the form. After tapping on the text field, when a keyboard is opened this field should be moved to the top part of the screen so a user will see what he is typing.~~
- User should be able to close the pop-up by flicking the screen to the right ( the opposite way from where it appears)
  ~~LANDSCAPE: image doesn't occupy the whole screen, there is a white stripe on the right side of the screen.~~

"CONTACT" SCREEN:
- ~~User should be able to close the pop-up by flicking the screen to the right ( the opposite way from where it appears)~~
- ~~Add underline below the phone number~~
- ~~When a user scrolls down from this screen it should slide-out of the screen right away, now you're able to scroll through several sections.~~
- ~~User shouldn't be able to click on the photo of the building ( same for the Desktop)~~
