### ISSUE TITLE
Remove "Showroom" from the content area and add it as a "Menu" item named "CONTACT" right above "ABOUT" when user clicks on it it should be opened n the content area just like "Showroom" page right now. If user scrolls down they should continue from the spot where they clicked "CONTACT" button 

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#108]
MOBILE: "Showroom" template should be opened when user clicks "Phone" icon in the upper corner of the screen

**Comment by TehZarathustra** [comment]
need testing

**Comment by Artemk23** [comment]
"Showroom" shouldn't be present at the main scrolling area, visitor should see it only by clicking on "Contact" item in the side Menu

**Comment by Artemk23** [comment]
1. "Contact" button should be the same height as other main menu items
2. "Contact" button should be dark at all times
3. Lines between "Contact&About" and "Manufacturers&Quickships" are thicker than other lines ( see screenshot below) - they should be the same size.

![screen shot 2016-10-16 at 10 20 11 pm](https://cloud.githubusercontent.com/assets/17010253/19426130/df761af2-93ee-11e6-92a8-34dec05a5325.png)
4. image of the building is not aligned properly, now it's located in the corner of the screen. Should like recently aligned correctly on the right side of the screen
5. "Request More Info" screen isn't fixed - shouldn't occupy the whole screen, but should be like "Contact" pop-up, only occupying content area, main menu should be visible
