### ISSUE TITLE
DESKTOP: Layout #9 is not displayed correctly ( screenshot)

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#17]
![screen shot 2016-04-25 at 8 48 16 am](https://cloud.githubusercontent.com/assets/17010253/14789707/a20c3936-0ac2-11e6-875d-1f88fff80c05.png)

**Comment by Artemk23** [comment]
Image should take their final position, and not overlap each other

**Comment by TehZarathustra** [comment]
it is expected behavior, animations were not applied

**Comment by Artemk23** [comment]
![laout 9](https://cloud.githubusercontent.com/assets/17010253/14789931/c697c0da-0ac3-11e6-9ba1-d6e2b21101dd.jpg)
ok, this is what is the final look should be
