### ISSUE TITLE
Create "Contact Us" Main Menu item which will have this layout and functionality.

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#26]
![contact - staff- option 3](https://cloud.githubusercontent.com/assets/17010253/15599017/b3fdfa68-2394-11e6-9bcb-7f50c611b619.jpg)

LAYOUT: We already have this layout: Image on the left text on the right.
FUNCTIONALITY: When visitor hover mouse over the name or any face system should make the image blurry except for the face, display email and phone below and on the right side all names should become semi transparent ( Like on the screenshot)

**Comment by Artemk23** [comment]
Image that we will use.
Do we need 6 different blurred images, which will work as a hover effect or you can make it?

**Comment by TehZarathustra** [comment]
yep, actually we will need seven images (one fully blurred and other six with each person unblurred)

**Comment by Artemk23** [comment]
[Staff page - images.zip](https://github.com/TehZarathustra/maven-static/files/287956/Staff.page.-.images.zip)

**Comment by Artemk23** [comment]
Position of the tables with email and phone number should be changed - "Contact Info" tag should be located below the center of the face 
1. ![screen shot 2016-06-01 at 10 58 49 am](https://cloud.githubusercontent.com/assets/17010253/15720140/f63ee14c-27e7-11e6-90d1-03bf3f3dcd82.png)
   Move it to the left and little bit lower, it's ok if it overlaps other person's head.
2. ![screen shot 2016-06-01 at 10 58 31 am](https://cloud.githubusercontent.com/assets/17010253/15720166/0d66f60c-27e8-11e6-8110-6e75202fc07c.png)
   ![screen shot 2016-06-01 at 10 58 23 am](https://cloud.githubusercontent.com/assets/17010253/15720171/154e84ca-27e8-11e6-9858-aaef30d068f5.png)
   ![screen shot 2016-06-01 at 10 58 19 am](https://cloud.githubusercontent.com/assets/17010253/15720175/17e64e3e-27e8-11e6-8c30-8690a3f74e8c.png)
   Move up so it will be closer to the face.

3.![screen shot 2016-06-01 at 10 57 19 am](https://cloud.githubusercontent.com/assets/17010253/15720195/293ad01a-27e8-11e6-9bb2-3d0e7d1bcf8a.png)
Shouldn't overlap the face - move down

**Comment by Artemk23** [comment]
This page is not responsive - when resolution changes "Contact Info" changes

**Comment by Artemk23** [comment]
If user clicks on the blurred area image should return to the default state - image should become sharp and non of the contact information should be displayed

**Comment by Artemk23** [comment]
1. Contact information's table (Email and Phone) should be displayed below the center of the face for all of the people on the picture.
   Should be displayed the same for all of these screen resolutions: 
   ![screen shot 2016-06-03 at 9 02 42 am](https://cloud.githubusercontent.com/assets/17010253/15785019/0917dcc8-296a-11e6-865f-ae030fb2deef.png)
