### ISSUE TITLE
DESKTOP & MOBILE: integrate "Pinterest" image hover plugin (link inside)

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#29]
**PINTEREST:** 
https://developers.pinterest.com/tools/widget-builder/?type=pinit&buttonType=imageHover&tall=false&color=white&round=true

**Comment by Artemk23** [comment]
**FACEBOOK:**
https://developers.facebook.com/docs/plugins/like-button#configurator

**Comment by TehZarathustra** [comment]
0544e5bb4cb50cd328afd183f338a6918a815e8e

**Comment by Artemk23** [comment]
![screen shot 2016-07-02 at 3 34 39 pm](https://cloud.githubusercontent.com/assets/17010253/16542753/aac3df2e-406a-11e6-8bb0-2ee8597c12bb.png)
1. Description shows "image" - should display image's title from the 'text area" (white text block in the corner)
2. Link behind the image should redirect to the Manufacturers brand page where this image was shared from

**Comment by Artemk23** [comment]
SLIDESHOW:
1. Click on "Pinterest" icon inside of the slideshow on the image other that the first one ( for example in "Senators Group, image number 3
![screen shot 2016-07-09 at 1 27 19 pm](https://cloud.githubusercontent.com/assets/17010253/16710116/1fa9d19a-45d9-11e6-89ba-66e2ec140947.png)
1. After clicking Pinterest widget's pop-up window opens.

ACTUAL RESULT: Pinterest widget recognizes default ( or first image from the slideshow) and not the image where "pinterest" icon was selected from
Expected Result: Visitor should be able to share image where he clicked Pinterest icon from in the slideshow
