### ISSUE TITLE
Add description to the image ( screenshot inside)

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#59]
![screen shot 2016-06-27 at 1 03 21 pm](https://cloud.githubusercontent.com/assets/17010253/16393949/b2fe7ce6-3c67-11e6-8b73-8862b61f642c.png)
for this product add this info:

**\- title:** i-Workchair

**\- text:** 
Premium Task Chair
i-Workchair is a premium task chair designed by Justus Kolberg to empower user individuality. After looking at the way we work, this intelligent seating solution has been developed to respond to a new range of postures.
- add "More Info" button which will redirect to this link: http://www.thesenatorgroup.com/americas/senator/seating/task-seating/i-workchair/?code=WRK340FD&color=Chrome/Blue/Grey
- "Request More Info" should stay as it is

**Comment by TehZarathustra** [comment]
"More info" is not implemented yet, we should discuss it.
As we have agreed caption has only 3 entities (title, text and "request more" button)

**Comment by Artemk23** [comment]
Add "More Details" button which redirect to this link in new browser's tab:
http://www.thesenatorgroup.com/americas/senator/seating/task-seating/i-workchair/?code=WRK340FD&color=Chrome/Blue/Grey
