### ISSUE TITLE
Images and pages layouts

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#72]
Archive with the final images here: 
[Final Images ( optimizied ).zip](https://github.com/TehZarathustra/maven-static/files/357942/Final.Images.optimizied.zip)
Our layouts - https://drive.google.com/open?id=0B_l53mChl5nmNmZwcjd0VzdGeVU

~~**IZZY +** - leave the main "izzy+" page as it is, just replace the slideshow with the newer version~~
~~\- **"Fixtures"** - layout 10 - vertical image should be in the center~~
~~\- **"HAG"** - layout 9 (stays the same)~~
~~\- **"Harter"** - Layout 8 ( slideshow)~~
~~\- **"Izzy"** - layout 7 (slideshow)~~

~~**"KRISTALIA"** - layout 10~~

~~**"OFS Brands"** - currently what we have at "Carolina" brand (logo, text, request more info and full width image)~~
~~\- **"Carolina"** - layout 2~~
~~\- **"First Office"** - layout 1 (slideshow)~~
~~\- **"Highmark"** - layout 5 (images with many chars should be as a slideshow for one of the placeholders)~~
~~\- **"Loewenstein"** - layout 6~~
~~\- **"OFS"** - Layout 10~~

~~**"Peter Pepper"** - layout 6~~

~~**"Senator Group"** - main page stays as it is~~
~~\- **"Allermuir"** - Layout 9: Conic.jpg, Famiglia.jpg and Open.jpg are the part of the slideshow for one of the placeholders. Cardita_Hero-copy.jpg - vertical image. Mote4.jpg - smallest placeholder~~
~~\- **"Senator"** - Layout 10~~

**Comment by TehZarathustra** [comment]
found a problem:
it seems that nor expanding image nor slider don't work in fifth layout

**Comment by TehZarathustra** [comment]
i've fixed server's images
issue is done, however i deliberately haven't changed Layouts in 'Allermiur' and 'Senator', to evade similarities (very next sections have same layouts)
