### ISSUE TITLE
DESKTOP - "Contact Us" form: Very end of the content area ( and after clicked "Request More Info) should have an updated layout ( INFO INSIDE)

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#78]
![kristalia_alt](https://cloud.githubusercontent.com/assets/17010253/16896974/6b53808a-4b58-11e6-8f78-072519f9dbc9.jpg)
**Where to be shown?**
~~**1.** in the very end of the content area after all of the section are past, this page should be displayed. No addition Menu Item should be added to the Main Menu, but title on the top of the page in the content area should say "Contact Us"~~
**2.** When visitor clicks "Request More Info" button

Background Image:
[Request-More-Info.jpg.zip](https://github.com/TehZarathustra/maven-static/files/367512/Request-More-Info.jpg.zip)

**Comment by TehZarathustra** [comment]
i'd suggest to leave "request more" as it is, it looks way cleaner on mobile

**Comment by Artemk23** [comment]
Mobile should display highlighted area - of course text should fit the screen
![6b53808a-4b58-11e6-8f78-072519f9dbc9 copy](https://cloud.githubusercontent.com/assets/17010253/17085207/bf21613e-5187-11e6-892b-26e6a2f67ef5.jpg)

**Comment by Artemk23** [comment]
Client requested to change the "Request More Info" they didn't like it
