### ISSUE TITLE
MOBILE - "Staff" page - image with people should stay on the top part of the screen until user scroll all of the names down or up

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/maven-static#91]

**Comment by TehZarathustra** [comment]
need testing

**Comment by Artemk23** [comment]
1. During the scroll more than half of the image gets hidden by the edge of the screen and then effect occurs. 
   EXPECTED RESULT: image should stop scrolling the moment it touches the top edge of the screen
2. When effect occurs image becomes full width ( no space between the side edges of the screen)
   EXPECTED RESULT: image should either stay the same or be full width all the time
3. Website should continue natural scroll approximately 20px after last's name information. Image should also be scrolled up.

**Comment by Artemk23** [comment]
![screen shot 2016-10-10 at 9 36 26 am](https://cloud.githubusercontent.com/assets/17010253/19243607/15f5e1ec-8ecd-11e6-99be-41c751f36394.png)
